name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Move to the test directory
        run: cd tests
      - name: Execute unit tests
        run: python run_all_tests.py
